#!/bin/bash

root="/media/NAS/photo/documents/sea-captains-chest"

dirs=()
dirs+=('diary-1828-and-1829-and-jan-1830')
dirs+=('diary-1830')
dirs+=('diary-1831')
dirs+=('diary-1832')
dirs+=('diary-1834')
dirs+=('diary-1835')
dirs+=('diary-1836')
dirs+=('diary-1837')
dirs+=('diary-1838')
dirs+=('diary-1839')


REPOSITORYURL="https://server.rsmaxwell.co.uk/archiva/repository"
REPOSITORYID="releases"
REPOSITORY="releases"
GROUPID="com.rsmaxwell.diary"

ARTIFACTID="diaryjson"

# find the latest version of the diaryjson jar
stdout=$(./getLatestJar "${REPOSITORYURL}" "${REPOSITORYID}" "${REPOSITORY}" "${GROUPID}" "${ARTIFACTID}")
result=$?
if [ ${result} -eq 0 ]; then
    diaryjsonJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

ARTIFACTID="generator"

# find the latest version of the generator jar
stdout=$(./getLatestJar "${REPOSITORYURL}" "${REPOSITORYID}" "${REPOSITORY}" "${GROUPID}" "${ARTIFACTID}")
result=$?
if [ ${result} -eq 0 ]; then
    generatorJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the CommonsCli Jar
stdout=$(./getJar "commons-cli" "commons-cli" "1.4")
result=$?
if [ ${result} -eq 0 ]; then
    commonsCliJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the JacksonDatabind Jar
stdout=$(./getJar "com.fasterxml.jackson.core" "jackson-databind" "2.10.2")
result=$?
if [ ${result} -eq 0 ]; then
    jacksonDataBindJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the JacksonCore Jar
stdout=$(./getJar "com.fasterxml.jackson.core" "jackson-core" "2.10.2")
result=$?
if [ ${result} -eq 0 ]; then
    jacksonCoreJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the JacksonAnnotations Jar
stdout=$(./getJar "com.fasterxml.jackson.core" "jackson-annotations" "2.10.2" )
result=$?
if [ ${result} -eq 0 ]; then
    jacksonAnnotationsJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf Jar
stdout=$(./getJar "com.itextpdf" "html2pdf" "2.1.6" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf forms Jar
stdout=$(./getJar "com.itextpdf" "forms" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfFormsJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf kernel Jar
stdout=$(./getJar "com.itextpdf" "kernel" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfKernelJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf io Jar
stdout=$(./getJar "com.itextpdf" "io" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfIOJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf layout Jar
stdout=$(./getJar "com.itextpdf" "layout" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfLayoutJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf svg Jar
stdout=$(./getJar "com.itextpdf" "svg" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfSvgJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the itextpdf styled-xml-parser Jar
stdout=$(./getJar "com.itextpdf" "styled-xml-parser" "7.1.9" )
result=$?
if [ ${result} -eq 0 ]; then
    itextpdfStyledXmlParserJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi

# get the slf4j-api Jar
stdout=$(./getJar "org.slf4j" "slf4j-api" "1.7.13" )
result=$?
if [ ${result} -eq 0 ]; then
    slf4jJar=${stdout}
else
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi



#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
if [ ! -d "${root}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "root not found: [${root}]"
    exit 1
fi

rm -rf temp
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mkdir -p "output/html/images" "output/fragments" "temp"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi




classpath="${extractorJar}:${diaryjsonJar}:${commonsCliJar}:${jacksonDataBindJar}:${jacksonCoreJar}:${jacksonAnnotationsJar}:${slf4jJar}"

#-------------------------------------------
# Extract text from the diary word files (*.docx) into html fragments (*.json)
#-------------------------------------------
for i in "${dirs[@]}"; do
    # echo "${i}"

    for file in "${root}/${i}/metadata/word"/*.docx; do

        basename=$(basename "${file}")

        regex="^img[0-9]{4}(-(left|right))?\.docx$"
        if [[ "${basename}" =~ ${regex} ]]; then

            makefile="output/dependancies/${basename%.*}.mk"
            if [ -f "${makefile}" ]; then
                make --file "${makefile}"
            else
                # Call the java extract program (which will also generate a makefile)
                call extract "${file}"
                result=$?
                if [ ! ${result} -eq 0 ]; then
                    echo "Error: $0[${LINENO}]"
                    echo "result: ${result}"
                    exit 1
                fi
            fi
        fi
    done

    # Copy the manually crafted fragments (usually links to images) straight into the fragments directory
    for file in "${root}/${i}/metadata/links"/*; do
        [ -f "${file}" ] || continue

        basename=$(basename "${file}")
        target="output/fragments/${basename}"

        if [ "${target}" -nt "${file}" ]; then
            : # echo "up-to-date: ${target}"
        else
            echo "updating: ${target}"
            cp "${file}" "${target}"
            result=$?
            if [ ! ${result} -eq 0 ]; then
                echo "Error: $0[${LINENO}]"
                echo "result: ${result}"
                echo "${stdout}"
                exit 1
            fi
        fi
    done

    # Copy the images to the html images directory
    for file in "${root}/${i}"/*; do
        [ -f "${file}" ] || continue

        basename=$(basename "${file}")

        regx="^img([0-9]{4})-image-.*\.(jpg|png)$"
        if [[ "${basename}" =~ ${regx} ]]; then

            # Copy the images to the html images directory
            target="output/html/images/${basename}"
            if [ "${target}" -nt "${file}" ]; then
                : # echo "up-to-date: ${target}"
            else
                echo "updating: ${target}"
                cp "${file}" "${target}"
            fi

            # Write out the dependancy info for this image
            fragment="${root}/${i}/metadata/links/${basename%.*}.json"
            if [ -f "${fragment}" ]; then
                year=$(jq '.year' "${fragment}")
                result=$?
                if [ ! ${result} -eq 0 ]; then
                    echo "Error: $0[${LINENO}]"
                    echo "result: ${result}"
                    echo "${stdout}"
                    exit 1
                fi

                echo ${basename} > "output/fragments/${year}.dep"
            else
                echo "Error: $0[${LINENO}]"
                echo "result: ${result}"
                echo "missing fragment link for image file: ${fragment}"
                exit 1
            fi
        fi
    done
done


# Copy the styles (*.css) to the html css directory
for file in styles/*.css; do
    [ -f "${file}" ] || continue

    basename=$(basename "${file}")

    target="output/html/css/${basename}"
    if [ "${target}" -nt "${file}" ]; then
        : # echo "up-to-date: ${target}"
    else
        echo "updating: ${target}"
        cp "${file}" "${target}"
        result=$?
        if [ ! ${result} -eq 0 ]; then
            echo "Error: $0[${LINENO}]"
            echo "result: ${result}"
            echo "${stdout}"
            exit 1
        fi
    fi
done


#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
if [ ! -d "${root}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "root not found: [${root}]"
    exit 1
fi

rm -rf temp
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mkdir -p "output/html/images" "output/fragments" "temp"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
call generate
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi
