#!/bin/bash

root="/media/NAS/photo/documents/sea-captains-chest"

dirs=()
dirs+=('diary-1828-and-1829-and-jan-1830')
dirs+=('diary-1830')
dirs+=('diary-1831')
dirs+=('diary-1832')
dirs+=('diary-1834')
dirs+=('diary-1835')
dirs+=('diary-1836')
dirs+=('diary-1837')
dirs+=('diary-1838')
dirs+=('diary-1839')

#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
if [ ! -d "${root}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "root not found: [${root}]"
    exit 1
fi

rm -rf temp
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mkdir -p "output/html/images" "output/html/css" "output/fragments" "temp"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi


#-------------------------------------------
# Export the build timestamp 
#-------------------------------------------
export BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
export BUILD_YEAR=$(date '+%Y')
export BUILD_MONTH=$(date '+%m')
export BUILD_DAY=$(date '+%d')

#-------------------------------------------
# Clear the dependancies 
#-------------------------------------------
rm -rf output/dependancies/*
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "make --file \"${makefile}\""
    exit 1
fi

declare -a makefiles=()

#-------------------------------------------
# Extract text from the diary word files (*.docx) into html fragments (*.json)
#-------------------------------------------
for i in "${dirs[@]}"; do
    echo "---[ ${i} ]------------"

    for file in "${root}/${i}/metadata/word"/*.docx; do

        basename=$(basename "${file}")

        regex="^img[0-9]{4}(-(left|right))?\.docx$"
        if [[ "${basename}" =~ ${regex} ]]; then

set -x
            makefile="output/dependancies/${basename%.*}.mk"
            if [ -f "${makefile}" ]; then

                # Call 'make' to call the java extract program
                echo "make --file \"${makefile}\""
                make --file "${makefile}"
                result=$?
                if [ ! ${result} -eq 0 ]; then
                    echo "Error: $0[${LINENO}]"
                    echo "result: ${result}"
                    echo "make --file \"${makefile}\""
                    exit 1
                fi
            else
                # Call the java extract program (which will also generate a makefile for next time round)
                echo "./extract \"${file}\""
                ./extract "${file}"
                result=$?
                if [ ! ${result} -eq 0 ]; then
                    echo "Error: $0[${LINENO}]"
                    echo "result: ${result}"
                    exit 1
                fi
            fi
echo "... exiting ..."
exit 99
        fi
    done

    # Copy the manually crafted fragments (usually links to images) straight into the fragments directory
    # for file in "${root}/${i}/metadata/fragments"/*; do
    #     [ -f "${file}" ] || continue
	# 
    #     basename=$(basename "${file}")
    #     target="output/fragments/${basename}"
	# 
    #     if [ "${target}" -nt "${file}" ]; then
    #         : # echo "up-to-date: ${target}"
    #     else
    #         echo "updating: ${target}"
    #         cp "${file}" "${target}"
    #         result=$?
    #         if [ ! ${result} -eq 0 ]; then
    #             echo "Error: $0[${LINENO}]"
    #             echo "result: ${result}"
    #             echo "${stdout}"
    #             exit 1
    #         fi
    #     fi
    # done

    # Copy the images and also their fragment dirs to output
    for file in "${root}/${i}"/*; do
        [ -f "${file}" ] || continue

        basename=$(basename "${file}")

        regx="^img([0-9]{4})-image-.*\.(jpg|png)$"
        if [[ "${basename}" =~ ${regx} ]]; then

            # Copy the images to the html images directory
            imageSource=${file}
            imageTarget="output/html/images/${basename}"
            if [ "${imageTarget}" -nt "${imageSource}" ]; then
                : # echo "up-to-date: ${imageTarget}"
            else
                echo "updating: ${imageTarget}"
                cp "${imageSource}" "${imageTarget}"
            fi

            extension="${basename##*.}"
            filename="${basename%.*}"

            # Check the image fragment exists
            fragment="${root}/${i}/metadata/fragments/${filename}"
            if [ ! -d "${fragment}" ]; then
                echo "Error: $0[${LINENO}]"
                echo "result: ${result}"
                echo "missing fragment for image file: ${fragment}"
                exit 1
            fi

            # Copy the image fragment dir to the output directory
            target="output/fragments/${filename}"
            if [ "${target}" -nt "${fragment}" ]; then
                : # echo "up-to-date: ${target}"
            else
                echo "updating: ${target}"
                mkdir -p "${target}"
            fi

            src="${fragment}/fragment.html"
            trg="${target}/fragment.html"
            if [ "${trg}" -nt "${src}" ]; then
                : # echo "up-to-date: ${trg}"
            else
                echo "updating: ${target}"
                cp -r "${src}" "${trg}"
            fi

            src="${fragment}/fragment.json"
            trg="${target}/fragment.json"
            if [ "${trg}" -nt "${src}" ]; then
                : # echo "up-to-date: ${trg}"
            else
                echo "updating: ${target}"
                cp -r "${src}" "${trg}"
            fi

            # Output the dependancies
            year=$(jq '.year' "${fragment}/fragment.json")
            result=$?
            if [ ! ${result} -eq 0 ]; then
                echo "Error: $0[${LINENO}]"
                echo "result: ${result}"
                echo "${stdout}"
                exit 1
            fi

            makefile="output/dependancies/${year}.mk"
            if [ ! -f "${makefile}" ]; then
                printf "${year}.html : " > ${makefile}
                makefiles+="${makefile}"
            fi
            printf "\\\n    ${target}/fragment.html" >> ${makefile}
            printf "\\\n    ${target}/fragment.json" >> ${makefile}
            printf "\\\n    ${imageTarget}" >> ${makefile}
        fi
    done
done

# Terminate the dependancy files
for makefile in "${makefiles[@]}"; do
    printf "\n" >> ${makefile}
done

#-------------------------------------------
# Copy the styles (*.css) to the html css directory
#-------------------------------------------
for file in input/styles/*; do
    [ -f "${file}" ] || continue

    basename=$(basename "${file}")

    target="output/html/css/${basename}"
    if [ "${target}" -nt "${file}" ]; then
        : # echo "up-to-date: ${target}"
    else
        echo "updating: ${target}"
        cp "${file}" "${target}"
        result=$?
        if [ ! ${result} -eq 0 ]; then
            echo "Error: $0[${LINENO}]"
            echo "result: ${result}"
            echo "${stdout}"
            exit 1
        fi
    fi
done

#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
./generate
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "${stdout}"
    exit 1
fi
