#!/bin/bash

configfile="${HOME}/diary.json"
if [ ! -f "${configfile}" ]; then
    echo "configfile not found: ${configfile}"
    exit 1
fi

#########################################################################################
# Read configuration
#########################################################################################
root=$(jq -r '.root' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi
if [ ! -d "${root}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "root not found: ${root}"
    exit 1
fi

path=$(jq -r '.path' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

diary=$(jq -r '.diary' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi
diaryPath="$(realpath ${root}/${path}/${diary})"
if [ ! -d "${diaryPath}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "diary not found: ${diaryPath}"
    exit 1
fi
imagesPath="$(realpath ${diaryPath}/metadata/images)"
if [ ! -d "${root}/${path}/${diary}/metadata/images" ]; then
    echo "Error: $0[${LINENO}]"
    echo "images not found: ${imagesPath}"
    exit 1
fi

year=$(jq -r '.year' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

input_fragments="input/fragments"
if [ ! -d "${input_fragments}" ]; then
    echo "directory not found ${input_fragments}"
    exit 1
fi

#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
rm -rf output/fragments output/html output/working
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mkdir -p "output/html/images/"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

#-------------------------------------------
# Copy the html elements (styles, scripts & control images)
#-------------------------------------------
cp -r "input/html" "output"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "file: ${file}"
    echo "target: ${target}"
    exit 1
fi

#-------------------------------------------
# Copy the images
#-------------------------------------------
echo "---[ ${diary} ]----------------------------"

readarray -d '' array < <(find ${imagesPath} \( -iname "*.jpeg" -or -iname "*.jpg" -or -iname "*.png" \) -print0)
for image in "${array[@]}"; do

    if [[ "${image}" == *"/@eaDir/"* ]]; then
        continue
    fi

    cp -r ${image} output/html/images/
    result=$?
    if [ ! ${result} -eq 0 ]; then
        echo "Error: $0[${LINENO}]"
        echo "result: ${result}"
        echo "make --file \"${makefile}\""
        exit 1
    fi
done

#-------------------------------------------
# Export the build timestamp 
#-------------------------------------------
export BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
export BUILD_YEAR=$(date '+%Y')
export BUILD_MONTH=$(date '+%m')
export BUILD_DAY=$(date '+%d')

#-------------------------------------------
# Generate the HTML documents from the fragments 
#-------------------------------------------
echo "generating diary for year: ${year}"
./generator input output ${year}
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi


