#!/bin/bash

configfile="${HOME}/diary.json"
if [ ! -f "${configfile}" ]; then
    echo "configfile not found: ${configfile}"
    exit 1
fi

#########################################################################################
# Read configuration
#########################################################################################
root=$(jq -r '.root' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi
if [ ! -d "${root}" ]; then
    echo "Error: $0[${LINENO}]"
    echo "root not found: ${root}"
    exit 1
fi

path=$(jq -r '.path' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

diaries=$(jq -r '.diaries' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

year=$(jq -r '.year' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

input_fragments="input/fragments"
if [ ! -d "${input_fragments}" ]; then
    echo "directory not found ${input_fragments}"
    exit 1
fi

#-------------------------------------------
# Check, clear and make directories 
#-------------------------------------------
rm -rf output/fragments output/html output/working
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

mkdir -p "output/html/images/"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

#-------------------------------------------
# Copy the html elements (styles, scripts & control images)
#-------------------------------------------
cp -r "input/html" "output"
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "file: ${file}"
    echo "target: ${target}"
    exit 1
fi

#-------------------------------------------
# Copy the images
#-------------------------------------------
for row in $(echo "${diaries}" | jq -r '.[] | @base64'); do

    diary=$(echo ${row} | base64 --decode)
    echo "---[ ${diary} ]----------------------------"

    diaryPath="$(realpath ${root}/${path}/${diary})"
    imagesPath="${diaryPath}/metadata/images"

    diaryPath="$(realpath ${root}/${path}/${diary})"
    if [ ! -d "${diaryPath}" ]; then
        echo "Error: $0[${LINENO}]"
        echo "diary not found: ${diaryPath}"
        exit 1
    fi
    imagesPath="$(realpath ${diaryPath}/metadata/images)"
    if [ ! -d "${root}/${path}/${diary}/metadata/images" ]; then
        echo "Error: $0[${LINENO}]"
        echo "images not found: ${imagesPath}"
        exit 1
    fi

    readarray -d '' array < <(find ${imagesPath} \( -iname "*.jpeg" -or -iname "*.jpg" -or -iname "*.png" \) -print0)
    for image in "${array[@]}"; do

        if [[ "${image}" == *"/@eaDir/"* ]]; then
            continue
        fi

        cp -r ${image} output/html/images/
        result=$?
        if [ ! ${result} -eq 0 ]; then
            echo "Error: $0[${LINENO}]"
            echo "result: ${result}"
            echo "make --file \"${makefile}\""
            exit 1
        fi
    done
done

#-------------------------------------------
# Export the build timestamp 
#-------------------------------------------
export BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
export BUILD_YEAR=$(date '+%Y')
export BUILD_MONTH=$(date '+%m')
export BUILD_DAY=$(date '+%d')

#-------------------------------------------
# Generate the HTML documents from the fragments 
#-------------------------------------------
echo "generating diary for year: ${year}"
./generator input output ${year}
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    exit 1
fi

#-------------------------------------------
# Generate an index.html pointing to the diaries
#-------------------------------------------
cat << EOF > output/html/index.html
<!DOCTYPE html>
<html>

<body>

<h1>Diaries</h1>

<ul>
    <li><a href="1828.html">1828</a><br>
    <li><a href="1829.html">1829</a><br>
    <li><a href="1830.html">1830</a><br>
    <li><a href="1831.html">1831</a><br>
    <li><a href="1832.html">1832</a><br>
    <li><a href="1834.html">1834</a><br>
</ul>


</body>
</html>

EOF
