#!/bin/bash

fragmentDir=$1
if [ -z "${fragmentDir}" ]; then
    echo "Missing fragmentDir argument"
    exit 1
fi
fragmentPath="input/fragments/${fragmentDir//\\//}"

fragment_html="${fragmentPath}/fragment.html"
if [ ! -f "${fragment_html}" ]; then
    echo "Fragment html not found: ${fragment_html}"
    exit 1
fi

fragment_json="input/fragments/${fragmentDir}/fragment.json"
if [ ! -f "${fragment_json}" ]; then
    echo "Fragment json not found: ${fragment_json}"
    exit 1
fi

stylesheet="input/styles/diary.css"
if [ ! -f "${stylesheet}" ]; then
    echo "stylesheet not found: ${stylesheet}"
    exit 1
fi

configfile="${HOME}/diary.json"
if [ ! -f "${configfile}" ]; then
    echo "configfile not found: ${configfile}"
    exit 1
fi

#########################################################################################
# Read configuration
#########################################################################################
root=$(jq -r '.root' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "fragment: ${fragment}"
    exit 1
fi

diary=$(jq -r '.diary' ${fragment_json})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "fragment: ${fragment}"
    exit 1
fi

source="${root}/${diary}/metadata/fragments"
if [ ! -d "${source}" ]; then
    echo "directory not found: ${source}"
    exit 1
fi

#########################################################################################
# Copy the image files 
#########################################################################################
copyImages=true

jq -e 'has("images")' ${fragment_json} > /dev/null;
result=$?
if [ ${result} -ne 0 ]; then
    copyImages=false
else
    images=$(jq -r '.images' "${fragment_json}")
    result=$?
    if [ ! ${result} -eq 0 ]; then
        echo "Error: $0[${LINENO}]"
        echo "result: ${result}"
        echo "fragment: ${fragment}"
        exit 1
    fi

    if [ ${images} == null ]; then
        copyImages=false
    fi
fi

if [ ${copyImages} == true ]; then

    for row in $(echo "${images}" | jq -r '.[] | @base64'); do
        _jq() {
         echo ${row} | base64 --decode | jq -r ${1}
        }

        filename=$(echo ${row} | base64 --decode)
        echo "image: ${filename}"

        mkdir -p ${fragmentPath}/images
        result=$?
        if [ ! ${result} -eq 0 ]; then
            echo "Error: $0[${LINENO}]"
            echo "result: ${result}"
            echo "fragment: ${fragment}"
            exit 1
        fi

        find ${source} -name ${filename} -exec cp {} ${fragmentPath}/images \;
        result=$?
        if [ ! ${result} -eq 0 ]; then
            echo "Error: $0[${LINENO}]"
            echo "result: ${result}"
            echo "fragment: ${fragment}"
            exit 1
        fi
    done
fi


document=${fragmentPath}/document.html
cat > ${document} << EOF
<html>
<head>
<link rel="stylesheet" type="text/css" href="../../../../styles/diary.css">
</head>
<body>
EOF

cat ${fragment_html} >> ${document}

cat >> ${document} << EOF
</body>
</html>
EOF








