#!/bin/bash

if [ -z "${SERVER_USERNAME}" ]; then
    echo "SERVER_USERNAME not specified"
    exit 1
fi

if [ -z "${SERVER_HOST}" ]; then
    echo "SERVER_HOST not specified"
    exit 1
fi

if [ -z "${SERVER_PORT}" ]; then
    echo "SERVER_PORT not specified"
    exit 1
fi

source="./output/html/"
target="${SERVER_USERNAME}@${SERVER_HOST}:/srv/httpd/htdocs/diaries"

array=()
array+=("--rsh" "ssh -p ${SERVER_PORT}")
array+=("--rsync-path=sudo -u www-data rsync")
array+=("--archive")
array+=("--compress")
array+=("--human-readable")
array+=("--delete")
array+=("--delete-excluded")
array+=("--stats")
array+=("${source}")
array+=("${target}")

delimiter="|"
options=""
for i in "${array[@]}"; do
    if [[ "${options}" == "" ]]; then
        options=${i}
    else
        options="${options}${delimiter}${i}"
    fi
done

OFS=${IFS}
IFS=${delimiter}
set -x
rsync ${options}
set +x
result=$?
IFS=${OFS}

if [ ! ${result} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi
