#!/bin/bash

. /opt/tasks/task-definitions

#########################################################################################
# Create a task to apply the feature
#########################################################################################
echo "Create a task to apply the feature"
taskDir=$(newTask)


#########################################################################################
# Create a task to configure the plain-text site
#########################################################################################
echo "Create a task to configure the plain-text site"
task=${tasksBase}/${taskDir}/task

cat >${task} <<'EOL'
#!/bin/bash

set -x 
sudo chown -R www-data:www-data html/
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi

sudo chmod -R 700 html/
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi

sudo rsync -avh --delete html/ /srv/httpd/htdocs/diaries
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi

EOL


#########################################################################################
# Populate the task with the run script and associated files
#########################################################################################
set -x
echo "Populate the task"

directory=$(pwd)
( cd ${tasksBase}/${taskDir}; mkdir -p ./html; cp -rs ${directory}/output/html/* ./html/ )
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi
set +x
#########################################################################################
# Run the task
#########################################################################################
echo "Run task"
machine="server"
runTask ${machine} ${taskDir}
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result = ${result}"
    exit 1
fi


