#!/bin/bash

fragmentDir=$1
if [ -z "${fragmentDir}" ]; then
    echo "Missing fragmentDir argument"
    exit 1
fi
fragmentPath="input/fragments/${fragmentDir//\\//}"

fragment_html="${fragmentPath}/fragment.html"
if [ ! -f "${fragment_html}" ]; then
    echo "Fragment html not found: ${fragment_html}"
    exit 1
fi

fragment_json="input/fragments/${fragmentDir}/fragment.json"
if [ ! -f "${fragment_json}" ]; then
    echo "Fragment json not found: ${fragment_json}"
    exit 1
fi

stylesheet="input/styles/diary.css"
if [ ! -f "${stylesheet}" ]; then
    echo "stylesheet not found: ${stylesheet}"
    exit 1
fi

configfile="${HOME}/diary.json"
if [ ! -f "${configfile}" ]; then
    echo "configfile not found: ${configfile}"
    exit 1
fi

#########################################################################################
# Read configuration
#########################################################################################

root=$(jq -r '.root' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "fragment: ${fragment}"
    exit 1
fi

diary=$(jq -r '.diary' ${configfile})
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "result: ${result}"
    echo "fragment: ${fragment}"
    exit 1
fi

source="${root}/${diary}/metadata/fragments"
if [ ! -d "${source}" ]; then
    echo "directory not found: ${source}"
    exit 1
fi

#########################################################################################
# Clean temporary files
#########################################################################################

file="input/fragments/${fragmentDir}/fragment.json"
json=$(cat ${file})
echo ${json} | jq . > ${file}
